### ISSUE TITLE
Blank page returned

### ISSUE THREAD

**Issue by freeever** [harshkoralwala/angular-micro-frontend#1]
hi, I run "npm i" for all the 3 sub apps, and followed the readme and started all the 4 apps.
All the 4 apps started successfully, however, when I access the following URLs, all returned blank page:

http://localhost:9000/
http://localhost:9000/admin
http://localhost:9000/bacancy/admin
http://localhost:4201/
http://localhost:4202/
http://localhost:4203/

And there were NOT errors in the browser dev tools console. Did I input the correct URLs?

**Comment by tanvishm** [comment]
I am also facing the same issue

**Comment by harshkoralwala** [comment]
That's Strange! @freeever @tanvishm 

Let me re-run the project and get back to you...

**Comment by harshkoralwala** [comment]
@freeever @tanvishm
 
Please take a pull...
it should work now

![image](https://github.com/harshkoralwala/angular-micro-frontend/assets/33347464/fed96676-830d-43dd-87df-c17bbb62c15d)

Updated Readme file,kindly follow updated steps
